import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  Poppins,
  Federo,
  Syne,
  Bodoni_Moda,
  Six_Caps,
  TikTok_Sans,
  Oswald,
  Archivo,
  Architects_Daughter,
  Manrope

} from "next/font/google";
import { Toaster } from 'sonner';



const architectsDaughter = Architects_Daughter({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-architects-daughter",
});


const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-manrope',
})

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins", //
});

const syne = Syne({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-syne", //
});

const oswald = Oswald({
  // Oswald typically supports 200 through 700
  weight: ["200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-oswald",
  display: 'swap',
});

const bodoni = Bodoni_Moda({
  weight: ["400", "900"], // 400 for body, 900 for high-end headers
  subsets: ["latin"],
  style: ["normal", "italic"],
  variable: "--font-bodoni", //
});

const archivo = Archivo({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  style: ["normal", "italic"], // <--- MUST ADD THIS
  variable: "--font-archivo",
});

const sixCaps = Six_Caps({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-six-caps", //
});

const federo = Federo({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-federo", //
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const tikTokSans = TikTok_Sans({
  subsets: ["latin"],
  variable: "--font-tiktok", 
  weight: "variable",
  display: "swap",
  adjustFontFallback: false, 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable}
          ${poppins.variable} 
          ${syne.variable} 
          ${bodoni.variable} 
          ${sixCaps.variable}
          ${federo.variable}
          ${tikTokSans.variable}
          ${oswald.variable}
          ${archivo.variable}
          ${manrope.variable}
          ${architectsDaughter.variable}
         antialiased`}
      >
        {children}
        <Toaster theme="dark" position="top-right" richColors />
      </body>
    </html>
  );
}
